// 메시지 도메인 엔티티 타입

// 메시지 타입 열거형
export enum MessageType {
  ADMIN = "admin",
  USER = "user",
  FILE = "file",
}

// 메시지 커스텀 타입 열거형
export enum MessageCustomType {
  SENDBIRD = "SENDBIRD:AUTO_EVENT_MESSAGE",
  BEFAMILY = "BEFAMILY:AUTO_EVENT_MESSAGE",
}

// 메시지 데이터 타입 열거형
export enum MessageInDataType {
  // SENDBIRD
  USER_JOIN = "USER_JOIN",
  USER_LEAVE = "USER_LEAVE",
  CHANNEL_KICK_USERS = "CHANNEL_KICK_USERS",
  CHANNEL_ASSIGN_MASTER = "CHANNEL_ASSIGN_MASTER",

  // BEFAMILY
  MESSAGE_BUBBLE = "MESSAGE_BUBBLE", //버블티콘
  MESSAGE_FILE = "MESSAGE_FILE", //파일 메시지
  MESSAGE_CONTACT = "MESSAGE_CONTACT", //연락처
  CHANNEL_CAPTURED = "CHANNEL_CAPTURED",
  MESSAGE_EMOTICON = "MESSAGE_EMOTICON",
  MESSAGE_SMILE_ME = "MESSAGE_SMILE_ME", //스마일미
  CHANNEL_NOTICE = "CHANNEL_NOTICE",
  MESSAGE_COMBINATION = "MESSAGE_COMBINATION",
  MESSAGE_COMBINATION2 = "MESSAGE_COMBINATION2",
  CHANNEL_INVITE = "CHANNEL_INVITE",
  MESSAGE_DELETED_ALL = "MESSAGE_DELETED_ALL",
  MESSAGE_DELETED_MY = "MESSAGE_DELETED_MY",
  ALBUM_ADD_PHOTO = "ALBUM_ADD_PHOTO",
  ALBUM_ADD_LIKE = "ALBUM_ADD_LIKE",
  DDAY_CREATED = "DDAY_CREATED",
  MESSAGE_DELETED = "MESSAGE_DELETED", //단일 메시지 삭제
  BEFAMILY_PROFILE_UPDATE = "BEFAMILY_PROFILE_UPDATE",
  UPDATE_TIMER_NOTI = "UPDATE_TIMER_NOTI", //대화방 타이머 설정
  UPDATED_TIMER_MESSAGE = "UPDATED_TIMER_MESSAGE", //대화방 타이머에 대한 메시지 삭제
  MESSAGE_DELETED_ALL_SCREEN = "MESSAGE_DELETED_ALL_SCREEN", // 대화방(모두) 단일 삭제
  DELETED_TIMER_MESSAGE = "DELETED_TIMER_MESSAGE", //삭제된 메시지 (어드민 메시지)
  MESSAGE_AFFILIATE = "MESSAGE_AFFILIATE", //재휴사 메시지
  MESSAGE_FAMILY_EVENT = "MESSAGE_FAMILY_EVENT", //가족행사 메시지
  MESSAGE_CALENDAR_EVENT = "MESSAGE_CALENDAR_EVENT", //캘린더 일정 메시지
  MESSAGE_DDAY_EVENT = "MESSAGE_DDAY_EVENT", //디데이 메시지
}

// 메시지 제어 타입 열거형
export enum MessageControlType {
  DEFAULT = "DEFAULT", // 기본
  COPY = "COPY", // 메세지 복사
  MY_MEMO = "MY_MEMO", // MY 메모
  RELAY = "RELAY", // 메세지 전달
  REPLY = "REPLY", // 메세지 답장
  DELETE_MY = "DELETE_MY", // 메시지 삭제(내화면)
  DELETE_ALL = "DELETE_ALL", // 메시지 삭제(친구화면까지)
}

// 메시지 콘텐츠 프로퍼티 (UI 컴포넌트에서 공유)
export type MessageContentProps = {
  message: any; // TODO: 구체적인 메시지 타입으로 대체
  chainTop?: boolean;
  chainBottom?: boolean;
};
