// 파일 종류
export enum FileKind {
  AUDIO = "AUDIO",
  DOCUMENT = "DOCUMENT",
  ETC = "ETC",
  GIF = "GIF",
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  WEBP = "WEBP",
  ZIP = "ZIP",
}

// 파일 카테고리
export enum FileCategory {
  ALBUM = "ALBUM",
  BACKUP = "BACKUP",
  CALENDAR = "CALENDAR",
  CHAT = "CHAT",
  COMMON = "COMMON",
  FEED = "FEED",
  POINT = "POINT",
  PROFILE = "PROFILE",
  RESOURCE = "RESOURCE",
  SMILE_ME = "SMILE_ME",
}

// 파일 하위 카테고리
export enum FileSubCategory {
  ALBUM_MEDIA = "ALBUM_MEDIA",
  ALBUM_THUMBNAIL = "ALBUM_THUMBNAIL",
  BACKUP = "BACKUP",
  CHAT_FILE = "CHAT_FILE",
  CHAT_MEDIA = "CHAT_MEDIA",
  CHAT_THUMBNAIL = "CHAT_THUMBNAIL",
  COMMON_IMAGE = "COMMON_IMAGE",
  COMMON_NOTICE = "COMMON_NOTICE",
  DDAY_BACKGROUND = "DDAY_BACKGROUND",
  DDAY_BACKGROUND_THUMBNAIL = "DDAY_BACKGROUND_THUMBNAIL",
  DDAY_BG_DEFAULT = "DDAY_BG_DEFAULT",
  DDAY_BG_DEFAULT_THM = "DDAY_BG_DEFAULT_THM",
  FEED = "FEED",
  POINT_MISSIONS = "POINT_MISSIONS",
  POINT_PRODUCTS = "POINT_PRODUCTS",
  PROFILE_ORIGIN = "PROFILE_ORIGIN",
  PROFILE_SMALL_THUMBNAIL = "PROFILE_SMALL_THUMBNAIL",
  PROFILE_THUMBNAIL = "PROFILE_THUMBNAIL",
  RESOURCE = "RESOURCE",
  SMILE_ME = "SMILE_ME",
}

// 미리보기 타입
export enum PreviewType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  ALBUM = "ALBUM",
  UNKNOWN = "UNKNOWN",
}
