import type { Metadata } from "next";
import ReactQueryProvider from "@/app/ReactQueryProvider";
import { OverlayRoot } from "@/shared/ui/overlays";
import "@/app/styles/default.css";
import "@/app/styles/global.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ReactQueryProvider>
          {children}
          <OverlayRoot />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
