export enum MessageCustomType {
  SENDBIRD = "SENDBIRD:AUTO_EVENT_MESSAGE",
  BEFAMILY = "BEFAMILY:AUTO_EVENT_MESSAGE",
}

export enum MessageType {
  ADMIN = "admin",
  USER = "user",
  FILE = "file",
}

export enum MessageDataType {
  // SENDBIRD
  USER_JOIN = "USER_JOIN",
  USER_LEAVE = "USER_LEAVE",
  CHANNEL_KICK_USERS = "CHANNEL_KICK_USERS",
  CHANNEL_ASSIGN_MASTER = "CHANNEL_ASSIGN_MASTER",

  // BEFAMILY
  MESSAGE_BUBBLE = "MESSAGE_BUBBLE", //버블티콘
  MESSAGE_FILE = "MESSAGE_FILE", //파일 메시지
  MESSAGE_CONTACT = "MESSAGE_CONTACT", //연락처
  CHANNEL_CAPTURED = "CHANNEL_CAPTURED",
  MESSAGE_EMOTICON = "MESSAGE_EMOTICON",
  MESSAGE_SMILE_ME = "MESSAGE_SMILE_ME", //스마일미
  CHANNEL_NOTICE = "CHANNEL_NOTICE",
  MESSAGE_COMBINATION = "MESSAGE_COMBINATION",
  MESSAGE_COMBINATION2 = "MESSAGE_COMBINATION2",
  CHANNEL_INVITE = "CHANNEL_INVITE",
  //WITH_DRAWAL = 'BEFAMILY:CHANNEL:WITH_DRAWAL',
  MESSAGE_DELETED_ALL = "MESSAGE_DELETED_ALL",
  MESSAGE_DELETED_MY = "MESSAGE_DELETED_MY",
  //ALBUM_CREATED = 'BEFAMILY:ALBUM:CREATED', //미사용
  ALBUM_ADD_PHOTO = "ALBUM_ADD_PHOTO",
  ALBUM_ADD_LIKE = "ALBUM_ADD_LIKE",
  //ALBUM_TAGGED = 'BEFAMILY:ALBUM:TAGGED', //미사용
  DDAY_CREATED = "DDAY_CREATED",
  MESSAGE_DELETED = "MESSAGE_DELETED", //단일 메시지 삭제
  BEFAMILY_PROFILE_UPDATE = "BEFAMILY_PROFILE_UPDATE",
  UPDATE_TIMER_NOTI = "UPDATE_TIMER_NOTI", //대화방 타이머 설정
  UPDATED_TIMER_MESSAGE = "UPDATED_TIMER_MESSAGE", //대화방 타이머에 대한 메시지 삭제
  //MESSAGE_DELETED_MY_SCREEN = 'MESSAGE_DELETED_MY_SCREEN', // 대화방(본인화면) 단일 삭제 (미사용 협의, deleteUsers 유무로 구분)
  MESSAGE_DELETED_ALL_SCREEN = "MESSAGE_DELETED_ALL_SCREEN", // 대화방(모두) 단일 삭제
  DELETED_TIMER_MESSAGE = "DELETED_TIMER_MESSAGE", //삭제된 메시지 (어드민 메시지)
  MESSAGE_AFFILIATE = "MESSAGE_AFFILIATE", //재휴사 메시지
  MESSAGE_FAMILY_EVENT = "MESSAGE_FAMILY_EVENT", //가족행사 메시지
  MESSAGE_CALENDAR_EVENT = "MESSAGE_CALENDAR_EVENT", //캘린더 일정 메시지
  MESSAGE_DDAY_EVENT = "MESSAGE_DDAY_EVENT", //디데이 메시지
}

export enum UIMessageType {
  // 시스템 메시지
  SYSTEM = "system",

  // 텍스트 메시지
  TEXT = "text",

  // 파일 메시지 (이미지, 비디오, 파일)
  FILE = "file",
  IMAGE = "image",
  VIDEO = "video",

  // 연락처 메시지
  CONTACT = "contact",

  // 답장 메시지
  REPLY = "reply",

  // CHECK: 미구현 메시지 (패밀리타운에서는 구현되어있음, 이모티콘, 행사)
  BUBBLE = "bubble",
  EVENT = "event",
}
